### ISSUE TITLE
Google Maps API error: ExpiredKeyMapError

### ISSUE THREAD

**Issue by kennedyrose** [escaladesports/react-store-locator#2]
I'm getting an error whenever an API key isn't provided.

> Google Maps API error: ExpiredKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#expired-key-map-error

![screen shot 2018-05-15 at 10 15 31 am](https://user-images.githubusercontent.com/1924910/40066107-083df78e-5829-11e8-9629-99eac808e527.png)

**Comment by tbaustin** [comment]
Tested not adding a key on the demo and it seems to work. Let me know if there are any other issues you find!
https://github.com/escaladesports/react-store-locator-demo
